---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment-catalog-history-service.yaml
  - service-catalog-history-service.yaml
images:
  - name: catalog-history-service
    newName: ghcr.io/informasjonsforvaltning/catalog-history-service
    newTag: $(GIT_COMMIT_SHA)
