name: Deploy to staging

on:
  pull_request:
    types: [ready_for_review, opened, reopened, synchronize]
    branches:
      - main

jobs:
  run-tests:
    name: Run tests
    uses: Informasjonsforvaltning/workflows/.github/workflows/coverage-go.yaml@main
    with:
      go_version: 1.23.6
      coverage_file_path: ./coverage.txt
      test_path: ./test
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  build-push:
    name: Build and push image to ghcr when pull request is created
    if: ${{ github.actor != 'dependabot[bot]' && github.event.pull_request.draft == false }}
    uses: Informasjonsforvaltning/workflows/.github/workflows/build-push.yaml@main
    with:
      app_name: catalog-history-service
      environment: staging
      build_env: true
      build_env_name: BINARY
      build_env_value: catalog-history-service
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    name: Deploy to staging environment
    needs: [ run-tests, build-push]
    uses: Informasjonsforvaltning/workflows/.github/workflows/kustomize-deploy.yaml@main
    with:
      app_name: catalog-history-service
      environment: staging
      cluster: digdir-fdk-dev
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      DIGDIR_FDK_AUTODEPLOY: ${{ secrets.DIGDIR_FDK_DEV_AUTODEPLOY }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
